### ISSUE TITLE
I did not succeed in the settings

### ISSUE THREAD

**Issue by alomar-mac** [nrwiersma/MMM-weather#1]
Hi

I did not succeed in the settings, is there any help in the steps?

thanks

**Comment by nrwiersma** [comment]
Can you post your config without the api key please?

**Comment by alomar-mac** [comment]
Please 
![Screen Shot 2020-04-13 at 3 41 44 PM](https://user-images.githubusercontent.com/47379574/79121308-a92f2c80-7d9d-11ea-95d9-f8ad238c0228.png)
![Screen Shot 2020-04-13 at 3 43 17 PM](https://user-images.githubusercontent.com/47379574/79121323-ac2a1d00-7d9d-11ea-9c82-cfc8d7a3eacc.png)

**Comment by nrwiersma** [comment]
Try this url with your config:
`https://api.openweathermap.org/data/2.5/forecast/daily?id=<locationID>&units=<config.units>&lang=<config.lang>&appid=<appid>`

For me <config.units> is `metric` and <config.lang> is `en`. It is possible your lang or units are the issue.

**Comment by alomar-mac** [comment]
Did not work with all following config steps as you mentioned
any how Thank you  :-(

**Comment by nrwiersma** [comment]
check open weather for the proper language and units and set them in the config as `lang` and `units`.

**Comment by alomar-mac** [comment]
I ma using "en" language and "metric" units

**Comment by nrwiersma** [comment]
Running `https://api.openweathermap.org/data/2.5/forecast/daily?id=109323&units=metric&lang=en&appid=<my appid>` gives me:
```
{
"city": {
"id": 109323,
"name": "Khobar",
"coord": {
"lon": 50.2083,
"lat": 26.2794
},
"country": "SA",
"population": 0,
"timezone": 10800
},
"cod": "200",
"message": 0.050033,
"cnt": 7,
...
```

Perhaps check your appid.

**Comment by alomar-mac** [comment]
{"cod":401, "message": "Invalid API key. Please see http://openweathermap.org/faq#error401 for more info."}

I am using openweathermap withe default Weather module it working good

**Comment by nrwiersma** [comment]
Yeah, sorry. Dont know how else to help. The issue seems to be with your api key (appid).

**Comment by alomar-mac** [comment]
it's okay sir thank you I'll check my API key
